name: escolar_app
description: "App de rastreamento de ônibus escolar — Paulo Afonso BA"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # GPS real do dispositivo
  geolocator: ^12.0.0

  # Mapa OpenStreetMap (sem chave de API)
  flutter_map: ^7.0.1

  # Coordenadas para flutter_map
  latlong2: ^0.9.1

  # Requisições HTTP para o backend Java
  http: ^1.2.1

  # Formatação de datas
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true